id: MaskRCNN_PennFudanPed
pretrained: null
seed: 3698
model:
    name: MaskRCNN_ResNet50_FPN
    args:
        nclasses: 2
optimizer:
    name: SGD
    args:
        lr: 0.005
        momentum: 0.9
        weight_decay: 0.0005
loss:
    name: DetectionLoss
    args:
metric: {}
scheduler:
    name: StepLR
    args:
        step_size: 3
        gamma: 0.1
dataset:
    trainval:
        ratio: 0.7
        name: PennFudanPed
        args:
            root: data/PennFudanPed
        loader:
            train:
                name: DataLoader
                args:
                    batch_size: 2
                    shuffle: True
                collate_fn: list_collate
            val:
                name: DataLoader
                args:
                    batch_size: 2
                collate_fn: list_collate
trainer:
    nepochs: 10
    val_step: 1
    log_step: 1
