id: MNIST
pretrained: null
seed: 3698
model:
    name: SpatialTransformerNet
    args:
        in_channels: 1
        feature_dim: 16
        nclasses: 10
optimizer:
    name: SGD
    args:
        lr: 0.01
loss:
    name: CrossEntropyLoss
    args:
metric:
    - name: Accuracy
      args:
scheduler:
    name: ReduceLROnPlateau
    args:
dataset:
    train:
        name: MNISTDataset
        args:
            path: data/MNIST/mnist_train.csv
        loader:
            name: DataLoader
            args:
                batch_size: 64
                shuffle: True
    val:
        name: MNISTDataset
        args:
            path: data/MNIST/mnist_test.csv
        loader:
            name: DataLoader
            args:
                batch_size: 64
trainer:
    nepochs: 50
    val_step: 1
    log_step: 1
